import os
import re
from html import escape
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas
from src.core.models import PipelineContext


class NumberedCanvas(canvas.Canvas):
    """Adds running headers and page numbers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#7f8c8d"))
        if self._pageNumber > 1:
            self.drawString(54, 750, "Autonomous Research Companion — Technical Manuscript")
            self.setStrokeColor(colors.HexColor("#bdc3c7"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_text)
        self.drawString(54, 36, "Generated by Autonomous Research Companion")
        self.setStrokeColor(colors.HexColor("#bdc3c7"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        self.restoreState()


def _md_inline_to_reportlab(text: str) -> str:
    """Minimal markdown → ReportLab XML (escape first, then restore simple markup)."""
    t = escape(text)
    t = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", t)
    t = re.sub(r"(?<!\*)\*(.+?)\*(?!\*)", r"<i>\1</i>", t)
    t = re.sub(r"`(.+?)`", r"<font face='Courier' size='8'>\1</font>", t)
    return t


class PDFExporter:
    """Renders PDF from Writer markdown_manuscript (primary), with optional metrics appendix."""

    @staticmethod
    def export(ctx: PipelineContext, output_filename: str) -> str:
        os.makedirs(os.path.dirname(output_filename) or ".", exist_ok=True)
        doc = SimpleDocTemplate(
            output_filename,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "PaperTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#2c3e50"),
            alignment=1,
            spaceAfter=12,
        )
        subtitle_style = ParagraphStyle(
            "PaperSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#7f8c8d"),
            alignment=1,
            spaceAfter=16,
        )
        h1_style = ParagraphStyle(
            "PaperH1",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#2c3e50"),
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True,
        )
        body_style = ParagraphStyle(
            "PaperBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2c3e50"),
            spaceAfter=8,
        )
        code_style = ParagraphStyle(
            "PaperCode",
            parent=styles["Code"],
            fontName="Courier",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#2c3e50"),
            backColor=colors.HexColor("#f8f9fa"),
            spaceAfter=8,
        )

        story = []
        story.append(Paragraph(escape(ctx.raw_topic), title_style))
        story.append(
            Paragraph(
                "Autonomous Research Companion &nbsp;|&nbsp; Multi-agent research draft",
                subtitle_style,
            )
        )
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#34495e"), spaceAfter=12))

        manuscript = (ctx.output.markdown_manuscript or "").strip()
        if manuscript:
            in_code = False
            code_buf = []
            for raw_line in manuscript.splitlines():
                line = raw_line.rstrip()
                if line.startswith("```"):
                    if in_code:
                        block = escape("\n".join(code_buf))
                        story.append(Paragraph(block.replace("\n", "<br/>"), code_style))
                        code_buf = []
                        in_code = False
                    else:
                        in_code = True
                    continue
                if in_code:
                    code_buf.append(line)
                    continue
                if line.startswith("# "):
                    story.append(Paragraph(_md_inline_to_reportlab(line[2:].strip()), title_style))
                elif line.startswith("## "):
                    story.append(Paragraph(_md_inline_to_reportlab(line[3:].strip()), h1_style))
                elif line.startswith("### "):
                    story.append(Paragraph(_md_inline_to_reportlab(line[4:].strip()), h1_style))
                elif line.startswith(("- ", "* ")):
                    story.append(Paragraph("• " + _md_inline_to_reportlab(line[2:].strip()), body_style))
                elif line.strip():
                    story.append(Paragraph(_md_inline_to_reportlab(line), body_style))
                else:
                    story.append(Spacer(1, 6))
        else:
            story.append(
                Paragraph(
                    "<i>No markdown manuscript available. Exporting metrics appendix only.</i>",
                    body_style,
                )
            )

        # Optional metrics appendix
        story.append(PageBreak())
        story.append(Paragraph("Appendix: Pipeline Metrics (non-authoritative)", h1_style))
        plag = ctx.quality_audit.plagiarism_percentage
        ai = ctx.quality_audit.ai_writing_percentage
        story.append(
            Paragraph(
                f"Heuristic QA (approximate): plagiarism≈{plag}% "
                f"({ctx.quality_audit.plagiarism_method}); "
                f"AI-style≈{ai}% ({ctx.quality_audit.ai_method}); "
                f"approved={ctx.quality_audit.is_approved}.",
                body_style,
            )
        )
        story.append(
            Paragraph(
                f"Code: {ctx.code_analysis.file_count} files, {ctx.code_analysis.total_lines} lines. "
                f"Critic score: {ctx.synthesis.critic_score}/100.",
                body_style,
            )
        )

        if ctx.synthesis.citations:
            story.append(Paragraph("References", h1_style))
            for idx, cite in enumerate(ctx.synthesis.citations, 1):
                authors_str = ", ".join(cite.authors[:3]) + (" et al." if len(cite.authors) > 3 else "")
                ref_str = f"[{idx}] {escape(authors_str)}, \"{escape(cite.title)},\" <i>{escape(cite.journal_or_arxiv)}</i>, {escape(cite.year)}."
                story.append(
                    Paragraph(
                        ref_str,
                        ParagraphStyle("RefLine", parent=body_style, fontSize=8.5, leading=11, spaceAfter=4),
                    )
                )

        doc.build(story, canvasmaker=NumberedCanvas)
        return output_filename
