import os
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
)
from reportlab.pdfgen import canvas
from src.core.models import PipelineContext


class NumberedCanvas(canvas.Canvas):
    """Adds running headers and page numbers (e.g. Page 1 of 5)."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#7f8c8d"))

        # Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(54, 750, "Autonomous Research Companion — Technical Manuscript")
            self.setStrokeColor(colors.HexColor("#bdc3c7"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_text)
        self.drawString(54, 36, "Confidential & Proprietary — Generated by AntiGravity Agent")
        self.setStrokeColor(colors.HexColor("#bdc3c7"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        self.restoreState()


class PDFExporter:
    """Renders a publication-ready PDF research paper."""

    @staticmethod
    def export(ctx: PipelineContext, output_filename: str) -> str:
        os.makedirs(os.path.dirname(output_filename), exist_ok=True)
        doc = SimpleDocTemplate(
            output_filename,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'PaperTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#2c3e50'),
            alignment=1, # Center
            spaceAfter=12
        )

        subtitle_style = ParagraphStyle(
            'PaperSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#7f8c8d'),
            alignment=1,
            spaceAfter=20
        )

        h1_style = ParagraphStyle(
            'PaperH1',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#8e44ad'),
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True
        )

        body_style = ParagraphStyle(
            'PaperBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=8
        )

        abstract_style = ParagraphStyle(
            'PaperAbstract',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9.5,
            leading=13.5,
            textColor=colors.HexColor('#34495e'),
            leftMargin=20,
            rightMargin=20,
            spaceAfter=14
        )

        code_style = ParagraphStyle(
            'PaperCode',
            parent=styles['Code'],
            fontName='Courier',
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor('#2c3e50'),
            backColor=colors.HexColor('#f8f9fa'),
            borderColor=colors.HexColor('#e9ecef'),
            borderWidth=1,
            borderPadding=6,
            spaceAfter=8
        )

        story = []

        # Title & Metadata
        story.append(Paragraph(f"Autonomous Analysis & Research Synthesis:<br/>{ctx.raw_topic}", title_style))
        story.append(Paragraph("<b>Authors:</b> AntiGravity Multi-Agent Research System &nbsp;|&nbsp; <b>Layer 6 Supervisor Engine</b><br/>Published via Autonomous Research Companion", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#8e44ad'), spaceAfter=15))

        # Abstract Box
        story.append(Paragraph("<b>ABSTRACT</b>", ParagraphStyle('AbsHeader', parent=h1_style, fontSize=11, leading=13, spaceAfter=4)))
        abstract_text = f"This manuscript presents an automated multi-agent investigation into <b>{ctx.raw_topic}</b>. By combining Layer 1 source code ingestion, Layer 2 AST complexity profiling, and Layer 3 academic literature retrieval via ArXiv, the system identifies structural implementation characteristics and establishes novelty gaps. Analysis of {ctx.code_analysis.file_count} source files totaling {ctx.code_analysis.total_lines} lines reveals key algorithmic patterns and Big-O performance boundaries. Synthesis validation by a Critic Agent scored {ctx.synthesis.critic_score}/100."
        story.append(Paragraph(abstract_text, abstract_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#bdc3c7'), spaceAfter=15))

        # 1. Introduction
        story.append(Paragraph("1. Introduction", h1_style))
        story.append(Paragraph(f"Modern software engineering and computer science research require seamless integration between code-level implementations and theoretical domain literature. This paper investigates <i>{ctx.raw_topic}</i> using a 6-layer supervised multi-agent framework.", body_style))
        story.append(Paragraph(f"The system processed background literature notes ({len(ctx.research.literature_summary)} characters) and style metrics: <b>{ctx.style_fingerprint.get('academic_tone', 'Formal')}</b> tone with <b>{ctx.style_fingerprint.get('sentence_length', 'Balanced')}</b> composition.", body_style))

        # 2. System Architecture & Code Analysis
        story.append(Paragraph("2. System Architecture & Code Analysis", h1_style))
        story.append(Paragraph(f"Static analysis of the repository identified <b>{len(ctx.code_analysis.function_blocks)}</b> primary function blocks across {ctx.code_analysis.file_count} files.", body_style))

        # Table: Algorithmic & Complexity Metrics
        if ctx.code_analysis.algorithms or ctx.code_analysis.complexities:
            table_data = [["Function / Module", "Detected Algorithm / Pattern", "Big-O Time & Space"]]
            for func_name, comp_str in list(ctx.code_analysis.complexities.items())[:6]:
                algo = ctx.code_analysis.algorithms[0]['name'] if ctx.code_analysis.algorithms else "Pipeline Module"
                table_data.append([func_name, algo, comp_str])

            if len(table_data) > 1:
                t = Table(table_data, colWidths=[140, 210, 150])
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8e44ad')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8.5),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                    ('TOPPADDING', (0, 0), (-1, -1), 5),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e1e8ed')),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')])
                ]))
                story.append(t)
                story.append(Spacer(1, 10))

        # 3. Research Grounding & Novelty Gaps
        story.append(Paragraph("3. Research Grounding & Novelty Gaps", h1_style))
        story.append(Paragraph("The Gap Finder agent evaluated system implementation traits against peer-reviewed literature, establishing the following research contribution gaps:", body_style))
        for gap in ctx.research.novelty_gaps:
            story.append(Paragraph(f"• <b>{gap}</b>", body_style))

        # 4. Hardware Mapping & Edge Cases
        story.append(Paragraph("4. Hardware Mapping & Edge Case Audit", h1_style))
        if ctx.code_analysis.bugs_edge_cases:
            story.append(Paragraph("The Bug & Edge Case agent detected potential runtime boundary conditions:", body_style))
            for b in ctx.code_analysis.bugs_edge_cases[:4]:
                story.append(Paragraph(f"• <b>{b.get('issue', 'Boundary Fault')}</b> (File: <i>{b.get('file', 'N/A')}</i>) — {b.get('impact', '')}", body_style))

        # 5. Conclusion & Recommendations
        story.append(Paragraph("5. Conclusion", h1_style))
        story.append(Paragraph(f"The multi-agent execution pipeline successfully synthesized code metrics and literature context for <b>{ctx.raw_topic}</b>. The Critic Agent assigned an overall manuscript quality score of <b>{ctx.synthesis.critic_score}/100</b>.", body_style))

        # References Section
        story.append(Spacer(1, 10))
        story.append(Paragraph("References", h1_style))
        for idx, cite in enumerate(ctx.synthesis.citations, 1):
            authors_str = ", ".join(cite.authors[:3]) + (" et al." if len(cite.authors) > 3 else "")
            ref_str = f"[{idx}] {authors_str}, \"{cite.title},\" <i>{cite.journal_or_arxiv}</i>, {cite.year}."
            story.append(Paragraph(ref_str, ParagraphStyle('RefLine', parent=body_style, fontSize=8.5, leading=11, spaceAfter=4)))

        doc.build(story, canvasmaker=NumberedCanvas)
        return output_filename
