import os
from typing import List, Dict, Any
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from src.core.models import PipelineContext


class PPTXExporter:
    """Renders a presentation deck matching the research paper."""

    @staticmethod
    def export(ctx: PipelineContext, output_filename: str) -> str:
        os.makedirs(os.path.dirname(output_filename), exist_ok=True)
        prs = Presentation()
        prs.slide_width = Inches(13.333) # 16:9 widescreen
        prs.slide_height = Inches(7.5)

        # Color Palette
        DARK_PURPLE = RGBColor(142, 68, 173) # #8e44ad
        NAVY_TEXT = RGBColor(44, 62, 80)     # #2c3e50
        MUTED_TEXT = RGBColor(127, 140, 141) # #7f8c8d
        BG_LIGHT = RGBColor(248, 249, 250)   # #f8f9fa
        WHITE = RGBColor(255, 255, 255)

        def add_header(slide, title_text, category_text="RESEARCH COMPANION"):
            # Header bar accent
            top_bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(0.12))
            top_bar.fill.solid()
            top_bar.fill.fore_color.rgb = DARK_PURPLE
            top_bar.line.fill.background()

            tx_box = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11.7), Inches(1.0))
            tf = tx_box.text_frame
            tf.word_wrap = True

            p0 = tf.paragraphs[0]
            p0.text = category_text.upper()
            p0.font.size = Pt(10)
            p0.font.bold = True
            p0.font.color.rgb = DARK_PURPLE

            p1 = tf.add_paragraph()
            p1.text = title_text
            p1.font.size = Pt(24)
            p1.font.bold = True
            p1.font.color.rgb = NAVY_TEXT

        # Slide 1: Title Slide
        blank_slide_layout = prs.slide_layouts[6]
        slide1 = prs.slides.add_slide(blank_slide_layout)

        # Background card shape
        bg_card = slide1.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.8), Inches(0.8), Inches(11.733), Inches(5.9))
        bg_card.fill.solid()
        bg_card.fill.fore_color.rgb = BG_LIGHT
        bg_card.line.color.rgb = DARK_PURPLE
        bg_card.line.width = Pt(2)

        t_box = slide1.shapes.add_textbox(Inches(1.2), Inches(1.5), Inches(10.9), Inches(4.5))
        tf = t_box.text_frame
        tf.word_wrap = True

        p = tf.paragraphs[0]
        p.text = "RESEARCH & CODE ANALYSIS PRESENTATION"
        p.font.size = Pt(12)
        p.font.bold = True
        p.font.color.rgb = DARK_PURPLE

        p2 = tf.add_paragraph()
        p2.text = ctx.raw_topic
        p2.font.size = Pt(32)
        p2.font.bold = True
        p2.font.color.rgb = NAVY_TEXT

        p3 = tf.add_paragraph()
        p3.text = f"\nGenerated by Layer 6 Supervisor Engine  |  Critic Score: {ctx.synthesis.critic_score}/100"
        p3.font.size = Pt(14)
        p3.font.color.rgb = MUTED_TEXT

        # Slide 2: System Architecture Overview
        slide2 = prs.slides.add_slide(blank_slide_layout)
        add_header(slide2, "6-Layer Multi-Agent Architecture Overview")

        t_box = slide2.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.0))
        tf = t_box.text_frame
        tf.word_wrap = True

        layers_info = [
            ("Layer 1: Input & Parsing", "Code Ingestor, Data Ingestor, Style Agent, Query Parser"),
            ("Layer 2: Code Analysis", "Code Breaker, Algo Detector, Complexity Analyzer, HW Mapper, Bug/Edge Case"),
            ("Layer 3: Research & Grounding", "ArXiv Agent, CS Agent, Electronics Agent, Literature Agent, Gap Finder"),
            ("Layer 4: Synthesis & Structure", "Connector, Outline Builder, Citation Agent, Critic Agent"),
            ("Layer 5: Output Generation", "Writer Agent, PDF Agent, PPT Agent")
        ]

        for title, desc in layers_info:
            p = tf.add_paragraph()
            p.text = f"• {title}: "
            p.font.size = Pt(15)
            p.font.bold = True
            p.font.color.rgb = NAVY_TEXT

            run = p.add_run()
            run.text = desc
            run.font.bold = False
            run.font.color.rgb = MUTED_TEXT

        # Slide 3: Code Analysis & Complexity Findings
        slide3 = prs.slides.add_slide(blank_slide_layout)
        add_header(slide3, "Code Analysis & Algorithmic Profiling", "LAYER 2 METRICS")

        t_box = slide3.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.0))
        tf = t_box.text_frame
        tf.word_wrap = True

        p = tf.paragraphs[0]
        p.text = f"Analyzed {ctx.code_analysis.file_count} files ({ctx.code_analysis.total_lines} lines of code)."
        p.font.size = Pt(16)
        p.font.bold = True
        p.font.color.rgb = NAVY_TEXT

        p_alg = tf.add_paragraph()
        p_alg.text = f"\nDetected Algorithms: {', '.join([a['name'] for a in ctx.code_analysis.algorithms])}"
        p_alg.font.size = Pt(14)
        p_alg.font.color.rgb = DARK_PURPLE

        for func, comp in list(ctx.code_analysis.complexities.items())[:4]:
            p_comp = tf.add_paragraph()
            p_comp.text = f"  • {func}(): {comp}"
            p_comp.font.size = Pt(13)
            p_comp.font.color.rgb = NAVY_TEXT

        # Slide 4: Novelty Gaps & Research Contributions
        slide4 = prs.slides.add_slide(blank_slide_layout)
        add_header(slide4, "Novelty Gaps & Literature Synthesis", "LAYER 3 & 4 GROUNDING")

        t_box = slide4.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.0))
        tf = t_box.text_frame
        tf.word_wrap = True

        for gap in ctx.research.novelty_gaps:
            p = tf.add_paragraph()
            p.text = f"✔ {gap}"
            p.font.size = Pt(15)
            p.font.color.rgb = NAVY_TEXT
            p.space_after = Pt(12)

        # Slide 5: References & Citations
        slide5 = prs.slides.add_slide(blank_slide_layout)
        add_header(slide5, "Peer-Reviewed References & Citations", "BIBLIOGRAPHY")

        t_box = slide5.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.0))
        tf = t_box.text_frame
        tf.word_wrap = True

        for idx, cite in enumerate(ctx.synthesis.citations, 1):
            p = tf.add_paragraph()
            authors_str = ", ".join(cite.authors[:3]) + (" et al." if len(cite.authors) > 3 else "")
            p.text = f"[{idx}] {authors_str}, \"{cite.title},\" {cite.journal_or_arxiv}, {cite.year}."
            p.font.size = Pt(13)
            p.font.color.rgb = NAVY_TEXT
            p.space_after = Pt(10)

        prs.save(output_filename)
        return output_filename
